# Nome do Workflow
name: Hacka-G11-Back Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout Repo
          uses: actions/checkout@v2

        - name: New Relic License
          run: |
            sed -i "s/licensekey/${{ secrets.NEW_RELIC_LICENSE_KEY }}/g" Dockerfile

        - name: Docker Login
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          run: | 
            echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
            cat key.json | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev/

        - name: Build Image & Push
          env: 
            ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
          run: | 
            docker build -t ${{ secrets.ARTIFACT_REGISTRY }}/spotmusic-backend:latest .
            docker push ${{ secrets.ARTIFACT_REGISTRY }}/spotmusic-backend:latest
    
        - id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

        - name: 'Deploy to Cloud Run'
          uses: 'google-github-actions/deploy-cloudrun@v0'
          with:
            image: '${{ secrets.ARTIFACT_REGISTRY }}/spotmusic-backend:latest'
            service: 'spotmusic-backend'